
spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8088
  datasource:
    url: jdbc:mysql://localhost:3306/payments?useSSL=false
    username: hungdx
    password: 2352002
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payments-group
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
