server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0



spring:
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: http://localhost:8084/
          predicates:
            - Path=/courses/**
        - id: detail-cate-service
          uri: http://localhost:8083/
          predicates:
            - Path=/api/detailcates/**
        - id: profile-service
          uri: http://localhost:8095/
          predicates:
            - Path=/api/profile/**