server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# config for zipkin
management:
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/category?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  flyway:
    baseline-on-migrate: true


